### PR TITLE
[DI-6682] Update examples

### PR DESCRIPTION
**Pull request by isturdy**
#### 🔖  Summary
Based on snapshots plus some unreleased logical type additions (https://github.com/Appboy/currents-users-events/pull/808)

#### 💪  Test Steps
- Spot checking

### CODE REVIEW

**Comment by flybonzai** [comment]
What process did you use here?  Do the avro snapshots include the schemas?

**Comment by isturdy** [comment]
Yes--they were written using the DataFileWriter, which I understand to include the schema. (And I haven't decoded any of the avro files, but the lack of consistent large file size reductions suggests this is accurate.)

It was written using a slight modification of the Snapshotter--I'm cleaning up a CUE PR including those changes now.

**Comment by flybonzai** [comment]
> Yes--they were written using the DataFileWriter, which I understand to include the schema. (And I haven't decoded any of the avro files, but the lack of consistent large file size reductions suggests this is accurate.)
> 
> It was written using a slight modification of the Snapshotter--I'm cleaning up a CUE PR including those changes now.

Let's test decoding them, it would be a bad look if customers can't use the examples.  `avro-tools` or python should be sufficient.

Can we also update the README for the examples in this repo with an example of how to decode them (using something like `avro-tools`).

**Comment by isturdy** [comment]
I've checked that the files can be parsed and do include the schema.

**Review by flybonzai — APPROVED** [review]

**Pull request merged**
