### PR TITLE
Added event table definitions

### PR DESCRIPTION
**Pull request by Anton-Shutik**
Added event table definitions

### CODE REVIEW

**Review by rogusdev — CHANGES_REQUESTED** [review]
Hi! Thanks for adding some content to this repo! However, this PR is a static list of field names and types, and as such it will require constant maintenance in its current form. If you instead submit a script that scrapes the files and generates a json object like this, I would approve that. But I do not want to add a static list like this that will get out of date or require manual attention.

**Comment by Anton-Shutik** [comment]
What files do you mean to scrape ? Those that are in `sample-data` ?

**Comment by rogusdev** [comment]
> What files do you mean to scrape ? Those that are in `sample-data` ?

How did you generate this list?

**Comment by Anton-Shutik** [comment]
Well, that was not that efficient. I used this [doc page](https://www.braze.com/docs/user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events/) and converted types by regex/hands

**Comment by rogusdev** [comment]
Thank you @Anton-Shutik -- I am investigating what we can recommend here, so please bear with me on the delay. I remain grateful for your engagement and willingness to help others, so I want to share that energy back to you soon!

**Comment by jayhahn** [comment]
Hi Anton

Thanks for opening this. We, unfortunately, don't have the resource to keep this updated so if you need a list of schemas, you can certainly extract them from the AVRO files in the sample-data. Each AVRO file will have the data schema in the beginning. That will be your best bet to getting up-to-date schema information.

**Pull request closed without merging**
